# CMake generated Testfile for 
# Source directory: /home/cg/dev/master-thesis/dev/src/c-cpp/Shark/examples
# Build directory: /home/cg/dev/master-thesis/dev/src/c-cpp/Shark/examples
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(SchwefelEllipsoidCMSA "SchwefelEllipsoidCMSA")
ADD_TEST(TSP_GA "TSP_GA")
ADD_TEST(ackleyES "ackleyES")
ADD_TEST(countingOnes "countingOnes")
ADD_TEST(integerES "integerES")
ADD_TEST(paraboloidCMA "paraboloidCMA")
ADD_TEST(paraboloidElitistCMA "paraboloidElitistCMA")
ADD_TEST(sphereGA "sphereGA")
ADD_TEST(steadyState "steadyState")
ADD_TEST(cblnsrch_test "cblnsrch_test")
ADD_TEST(covar_corrcoef_test "covar_corrcoef_test")
ADD_TEST(detsymm_test "detsymm_test")
ADD_TEST(dlinmin_test "dlinmin_test")
ADD_TEST(eigenerr_test "eigenerr_test")
ADD_TEST(eigensort_test "eigensort_test")
ADD_TEST(eigensymmJacobi2_test "eigensymmJacobi2_test")
ADD_TEST(eigensymmJacobi_test "eigensymmJacobi_test")
ADD_TEST(eigensymm_test "eigensymm_test")
ADD_TEST(fft_test "fft_test")
ADD_TEST(g_inverse_matrix "g_inverse_matrix")
ADD_TEST(linalg_simple_test "linalg_simple_test")
ADD_TEST(linmin_test "linmin_test")
ADD_TEST(lnsrch_test "lnsrch_test")
ADD_TEST(rank_decomp_test "rank_decomp_test")
ADD_TEST(rank_test "rank_test")
ADD_TEST(svd_test "svd_test")
ADD_TEST(svdrank_test "svdrank_test")
ADD_TEST(svdsort_test "svdsort_test")
ADD_TEST(mg-example "mg-example")
ADD_TEST(rbfn-example "rbfn-example")
ADD_TEST(HypervolumeBenchmark "HypervolumeBenchmark" "/home/cg/dev/master-thesis/dev/src/c-cpp/Shark/examples/MOO-EALib/ran.40000pts.3d.1")
ADD_TEST(RMMEDAtest "RMMEDAtest")
ADD_TEST(fonMO-CMA "fonMO-CMA")
ADD_TEST(fonSteadyStateMO-CMA "fonSteadyStateMO-CMA")
ADD_TEST(realcoded-NSGA2 "realcoded-NSGA2")
ADD_TEST(CrossValidation "CrossValidation")
ADD_TEST(FisherLDA "FisherLDA")
ADD_TEST(KM "KM")
ADD_TEST(KNN "KNN")
ADD_TEST(KalmanFilterTest "KalmanFilterTest")
ADD_TEST(KernelOptimization "KernelOptimization")
ADD_TEST(LinearClassifierTest "LinearClassifierTest")
ADD_TEST(LinearRegressionTest "LinearRegressionTest")
ADD_TEST(McSvm "McSvm")
ADD_TEST(PCAtest "PCAtest")
ADD_TEST(SVMclassification "SVMclassification")
ADD_TEST(SVMregression "SVMregression")
ADD_TEST(SvmApproximationExample "SvmApproximationExample")
ADD_TEST(simpleFFNet "simpleFFNet")
ADD_TEST(simpleFFNetSource "simpleFFNetSource")
ADD_TEST(simpleMSERNNet "simpleMSERNNet" "/home/cg/dev/master-thesis/dev/src/c-cpp/Shark/examples/ReClaM/timeseries")
ADD_TEST(simpleRBFNet "simpleRBFNet")
ADD_TEST(simpleRNNet "simpleRNNet")
ADD_TEST(RngTest "RngTest")
ADD_TEST(RngTest2 "RngTest2")
ADD_TEST(RngTestSimple "RngTestSimple")
ADD_TEST(embeddingTest "embeddingTest")
ADD_TEST(lorenz84 "lorenz84")
